Add ruok metric
signalfx/collectd-zookeeper pull request #5
Opened 2016-09-20 18:40 UTC by aeuio

zk_service_health is the new metric - add this to all stats collectd.

2016-09-22 00:54 UTC, mpetazzoni requested changes
I would have the `ZooKeeperServer` class make both `ruok` and `mntr` checks in its `get_stats()` method, instead of instantiating two of them only to have it do some special casing to call `_parse_ok()` or `_parse()`.

2016-09-22 15:03 UTC, aeuio commented
Fixed!

2016-09-22 17:17 UTC, mpetazzoni commented on zk-collectd.py
> +                results = self._parse_ok(data)
So, again, if you have to special case here inside a loop, it makes using a loop somewhat meaningless. Just do:

```python
def get_stats(self):
    stats = {}
    stats.update(self._get_health_stats())
    stats.update(self._get_mntr_stats())
    # We can add more metrics here in the future.
    return stats

def _get_health_stat(self):
    response = self._send_cmd(RUOK_CMD)
    return {'zk_service_health': int(response == IMOK_RESP)}

def _get_mntr_stats(self):
    response = self._send_cmd(MNTR_CMD)
    result = {}
    for line in response.splitlines():
        try:
            key, value = self._parse_line(line)
            if key == 'zk_server_state':
                result['zk_is_leader'] = int(value != 'follower')
            elif key == 'zk_version':
                continue
            else:
                result[key] = value
    return result
```

2016-09-22 17:18 UTC, mpetazzoni commented on zk-collectd.py
> -            except socket.error:
Is it safe to let this error bubble up? Doesn't collectd automatically disable a plugin if it errors out too much?

2016-09-22 17:18 UTC, mpetazzoni requested changes

2016-09-22 18:32 UTC, aeuio commented on zk-collectd.py
> -            except socket.error:
I replaced it with a log - it was there originally so i left it alone

2016-09-22 18:33 UTC, aeuio commented on zk-collectd.py
> +                results = self._parse_ok(data)
Fixed it up!

2016-09-22 18:34 UTC, aeuio commented
Thanks again!  Wasn't sure how much i should be changing anything because I was adding things so this was really helpful feedback.

2016-09-25 05:56 UTC, mpetazzoni approved these changes

2016-09-25 05:57 UTC, mpetazzoni commented
LGTM. Can you confirm you've tested your latest changes?

2016-09-26 15:26 UTC, aeuio commented
Thanks Max!  Yes, tested both success and failure conditions before i made the commit.

2016-09-27 13:28 UTC, merged